let friends = {
    'Ethan Johnson': 'images/profile_pictures/m1.avif',
    'Olivia Smith': 'images/profile_pictures/w1.avif',
    'Noah Williams': 'images/profile_pictures/m2.avif',
    'Ava Brown': 'images/profile_pictures/w2.avif',
    'Liam Davis': 'images/profile_pictures/m3.avif',
    'Sophia Miller': 'images/profile_pictures/w3.avif',
    'Mason Wilson': 'images/profile_pictures/m4.avif',
    'Isabella Moore': 'images/profile_pictures/w4.avif',
    'James Taylor': 'images/profile_pictures/m5.avif',
    'Mia Anderson': 'images/profile_pictures/w5.avif',
    'Lucas Thomas': 'images/profile_pictures/m6.avif',
    'Charlotte Jackson': 'images/profile_pictures/w6.avif',
    'Benjamin White': 'images/profile_pictures/m7.avif',
    'Amelia Harris': 'images/profile_pictures/w7.avif',
    'Elijah Martin': 'images/profile_pictures/m8.avif',
    'William Garcia': 'images/profile_pictures/m1.avif',
    'Emma Martinez': 'images/profile_pictures/w1.avif',
    'Alexander Robinson': 'images/profile_pictures/m2.avif',
    'Sofia Clark': 'images/profile_pictures/w2.avif',
    'Michael Rodriguez': 'images/profile_pictures/m3.avif',
    'Emily Lewis': 'images/profile_pictures/w3.avif',
    'Matthew Lee': 'images/profile_pictures/m4.avif',
    'Isabella Walker': 'images/profile_pictures/w4.avif',
    'Daniel Hall': 'images/profile_pictures/m5.avif',
    'Madison Allen': 'images/profile_pictures/w5.avif',
    'David Young': 'images/profile_pictures/m6.avif',
    'Grace Scott': 'images/profile_pictures/w6.avif',
    'Jacob Green': 'images/profile_pictures/m7.avif',
    'Ava Adams': 'images/profile_pictures/w7.avif',
    'Logan Hernandez': 'images/profile_pictures/m8.avif',
    'Sophia King': 'images/profile_pictures/w1.avif',
    'Jackson Carter': 'images/profile_pictures/m2.avif',
    'Olivia Hill': 'images/profile_pictures/w2.avif',
    'Gabriel Martinez': 'images/profile_pictures/m3.avif',
    'Sophia Price': 'images/profile_pictures/w3.avif',
    'Ryan Morris': 'images/profile_pictures/m4.avif',
    'Chloe Ward': 'images/profile_pictures/w4.avif',
    'Isaac Rivera': 'images/profile_pictures/m5.avif',
    'Ella Bailey': 'images/profile_pictures/w5.avif',
    'Samuel Reed': 'images/profile_pictures/m6.avif',
    'Lily Cooper': 'images/profile_pictures/w6.avif',
    'Anthony Torres': 'images/profile_pictures/m7.avif',
    'Zoe Peterson': 'images/profile_pictures/w7.avif',
    'Christopher Brooks': 'images/profile_pictures/m8.avif'
};


let posts={
    0:{
        'name':'Shashank Saini',
        'profile image':'images/profile_pictures/myprofile.png',
        'upload time':"4 days ago",
        'caption':'having a good day',
        'post image':"images/posts/post1.jpg",
        'likes':455,
        'comments':123,
        "share":99
        },
    1:{
        'name':'Olivia smith',
        'profile image':'images/profile_pictures/w1.avif',
        'upload time':'3 days ago',
        'caption':'mountains and river are my favorites',
        'post image':'images/posts/post2.avif',
        'likes':300,
        'comments':139,
        'share':21
    },
    2:{
        'name':'Benjamin White',
        'profile image':'images/profile_pictures/m7.avif',
        'upload time':'20 hours ago',
        'caption':'what a lovely day it was',
        'post image':'images/posts/post3.avif',
        'likes':203,
        'comments':22,
        'share':5,
    },
    3:{
        'name':'Shashank Saini',
        'profile image':'images/profile_pictures/myprofile.png',
        'upload time':'20 minutes ago',
        'caption':'successfully completed our annual fest',
        'post image':'images/posts/post5.jpg',
        'likes':340,
        'comments':76,
        'share':11,
    },
    4:{
        'name':'Sophia Miller',
        'profile image':'images/profile_pictures/w3.avif',
        'upload time':'2 days ago',
        'caption':'thanks to everyone',
        'post image':'images/posts/post4.avif',
        'likes':880,
        'comments':546,
        'share':112,
    },
    5:{
        'name':'Ava Brown',
        'profile image':'images/profile_pictures/w2.avif',
        'upload time':'1 day ago',
        'caption':'what a lovely place #japan',
        'post image':'images/posts/post6.avif',
        'likes':535,
        'comments':200,
        'share':134,
    },
    6:{
        'name':'Shashank Saini',
        'profile image':'images/profile_pictures/myprofile.png',
        'upload time':'4 hours ago',
        'caption':'Team Computer Science',
        'post image':'images/posts/post7.jpg',
        'likes':950,
        'comments':345,
        'share':56,
    }
}
